### ISSUE TITLE
Save Data from Phoenix App In Flutter

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/flutter-counter-example#3]
My next goal is to learn how to make an extension of a Flutter application to be able to save data of a Phoenix App using the Rest API.

**Comment by miguelmartins17** [comment]
While I was looking for information on the Rest API.


![Screen Shot 2020-03-24 at 11 54 52](https://user-images.githubusercontent.com/27420533/77423115-92ad3b00-6dc6-11ea-8b1e-2b5599cd5fc7.png)

**Comment by nelsonic** [comment]
Closing in favour of: #5
